// Copyright (c) 2021 Pierce Bartine. All rights reserved.
// Use of this source code is governed by the MIT License that can be found in
// the LICENSE file.

package main

import (
	"context"
	"fmt"
	"io/ioutil"
	"strings"

	"github.com/rs/zerolog/log"
	flag "github.com/spf13/pflag"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
	"k8s.io/client-go/tools/clientcmd/api"
)

const saveMethodKubeSecret = "kube-secret"

var (
	flagKubeconfig            = flag.String("kubeconfig", "", "Path to Kubeconfig to use when saving the Kubernetes secret. If unset, will attempt to use in-cluster config.")
	flagKubeSecretName        = flag.String("kube-secret-name", "vault-init", "Name of the Kubernetes secret to save Vault init result")
	flagKubeSecretNamespace   = flag.String("kube-secret-namespace", "", "Namespace to create the Kubernetes secret in. Defaults to the current namespace.")
	flagKubeSecretLabels      = flag.StringToString("kube-secret-labels", nil, "Labels to add to the Kubernetes secret")
	flagKubeSecretAnnotations = flag.StringToString("kube-secret-annotations", nil, "Labels to add to the Kubernetes secret")
)

func saveFnKubeSecret(r *initResult) (string, error) {
	// create kube api client and attempt to set namespace
	kube, err := newKubeClient(*flagKubeconfig)
	if err != nil {
		return "", err
	}
	ns := *flagKubeSecretNamespace
	if ns == "" {
		log.Info().Msg("reading namespace from serviceaccount token mount")
		nsBytes, err := ioutil.ReadFile("/var/run/secrets/kubernetes.io/serviceaccount/namespace")
		if err != nil {
			log.Warn().Err(err).Msg("unable to read namespace, falling back to default")
			ns = "default"
		} else {
			ns = string(nsBytes)
		}
	}
	log.Info().Str("namespace", ns).Msg("using namespace")

	// to avoid losing vault init data: if secret with desired name already exists, use it as prefix for autogenerated secret name instead
	metadata := metav1.ObjectMeta{
		Labels:      *flagKubeSecretLabels,
		Annotations: *flagKubeSecretAnnotations,
	}
	existing, err := kube.CoreV1().Secrets(ns).Get(context.TODO(), *flagKubeSecretName, metav1.GetOptions{})
	if err != nil && !strings.Contains(err.Error(), "not found") || err == nil && existing.Name == *flagKubeSecretName {
		log.Warn().Err(err).Msg("using name prefix for kube secret")
		metadata.GenerateName = fmt.Sprintf("%s-", *flagKubeSecretName)
	} else {
		metadata.Name = *flagKubeSecretName
	}

	// create the secret
	secret, err := kube.CoreV1().Secrets(ns).Create(context.TODO(), &corev1.Secret{
		ObjectMeta: metadata,
		Data: map[string][]byte{
			"vault-init.json": r.ResponseJSON,
			"root_token":      []byte(r.RootToken),
		},
	}, metav1.CreateOptions{})
	if err != nil {
		return "", err
	}

	return fmt.Sprintf("%s/%s", secret.Namespace, secret.Name), nil
}

// newKubeClient creates a Kubernetes API client from a kubeconfig file. If no file is passed, falls back to in-cluster config.
func newKubeClient(kubeconfigPath string) (*kubernetes.Clientset, error) {
	// attempt to use in-cluster config
	if kubeconfigPath == "" {
		config, err := rest.InClusterConfig()
		if err != nil {
			return nil, err
		}
		clientset, err := kubernetes.NewForConfig(config)
		if err != nil {
			return nil, err
		}
		return clientset, nil
	}

	// load kubeconfig from file
	config, err := clientcmd.BuildConfigFromKubeconfigGetter("", func() (*api.Config, error) {
		return clientcmd.LoadFromFile(kubeconfigPath)
	})
	if err != nil {
		return nil, err
	}
	return kubernetes.NewForConfig(config)
}
