version: '3'

# WARNING: Order matters here
vars:
  BIN:
    sh: basename "${PWD}"
  IMAGE: ghcr.io/pbar1/{{.BIN}}
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "unknown"

tasks:
  default: task --list

  clean:
    desc: Remove generated files from the working tree
    cmds:
    - cargo clean

  version:
    desc: Print version string that will be used
    cmds:
    - echo {{.VERSION}}

  image:
    desc: Alias for "image:build"
    deps:
    - image:build

  image:name:
    desc: Print container image name that will be used
    cmds:
    - echo {{.IMAGE}}:{{.VERSION}}

  # TODO: Implement multiplatform container images with --platform
  image:build:
    desc: Build container image
    cmds:
    - nix build .#dockerImage && ./result | docker load

  image:push:
    desc: Push container image to remote repository
    deps:
    - image:build
    cmds:
    - docker push {{.IMAGE}}:latest # FIXME:

  k3d:import:
    desc: Imports container image into local K3d cluster
    deps:
    - image:build
    cmds:
    - k3d image import {{.IMAGE}}:local
