name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: pbar1
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build . -A defaultPackage.x86_64-linux
