name: Push

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable

    - uses: cachix/cachix-action@v12
      with:
        name: pbar1
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - run: nix build .#defaultPackage.x86_64-linux

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push container image
      run: |
        nix build .#dockerImage && ./result | docker load
        docker push ghcr.io/pbar1/vault-init:latest
